// Code generated by "stringer -type eLogType -linecomment"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eLogType_Debug-0]
	_ = x[eLogType_Info-1]
	_ = x[eLogType_Waring-2]
	_ = x[eLogType_Error-3]
}

const _eLogType_name = "[DEBUG][INFO][WARN][ERROR]"

var _eLogType_index = [...]uint8{0, 7, 13, 19, 26}

func (i eLogType) String() string {
	if i < 0 || i >= eLogType(len(_eLogType_index)-1) {
		return "eLogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eLogType_name[_eLogType_index[i]:_eLogType_index[i+1]]
}
